### ISSUE TITLE
Getting and setting Cookies

### ISSUE THREAD

**Issue by Xonshiz** [elcattivo/CloudFlareUtilities#14]
Hey, I just started using C# and I was looking into this PCL. I got it working after looking at examples and everything. I was wondering if it was possible to get the `Cookies` from the connection and using storing and sending those `Cookies` when a new connection is made.

If that can be done, could you please post an example? Thanks for this lib. anyways :)

**Comment by kade-robertson** [comment]
By default, `HttpClient` disposes it's handler after the first use, even if you make multiple requests. You can make use of the `InnerHandler` property of the `ClearanceHandler`, set this to be an `HttpClientHandler` which you can define to store cookies, and then set up the `HttpClient` to not dispose the handler. Something like this should work:

```
var cookieContainer = new CookieContainer();
using (var cfHandler = new ClearanceHandler()) {
    cfHandler.InnerHandler = new HttpClientHandler() {
        UseCookies = true,
        CookieContainer = cookieContainer
    };
    using (var client = new HttpClient(cfHandler, false)) {
        // do stuff here..
    }
}
```

**Comment by Xonshiz** [comment]
Sorry, but I didn't get the code. Care to explain a little?
I wanted to connect to a site and grab all the cookies that the website makes for this particular connection and then pass these cookies to another instance of the client to use those cookies and connect to that website. How should I approach this in c#?

I've been writing in Python and it being Python, it was pretty easy. This is still confusing for me.

**Comment by elcattivo** [comment]
Here is another example:

```csharp
// Shared CookieContainer, that will contain all cookies
var cookies = new CookieContainer();

// First client instance
var client1 = new HttpClient(new ClearanceHandler(new HttpClientHandler
{
    UseCookies = true,
    CookieContainer = cookies // setting the shared CookieContainer
}));

client1.GetStringAsync("http://target.site");

// Second client instance
var client2 = new HttpClient(new ClearanceHandler(new HttpClientHandler
{
    UseCookies = true,
    CookieContainer = cookies // setting the shared CookieContainer
}));

client2.GetStringAsync("http://target.site");
```

**Comment by Xonshiz** [comment]
Thanks :+1:
