### ISSUE TITLE
Proxy?

### ISSUE THREAD

**Issue by kryptodev** [elcattivo/CloudFlareUtilities#15]
Hi, 

I'm actually learning c# and while trying to use this library I wanted to pass proxy into the handler, can I not do that?

Kindly guide me as to how I can pass proxy to the handler.

Thank you.

**Comment by elcattivo** [comment]
The `ClearanceHandler` is just a layer between the [HttpClient](https://msdn.microsoft.com/en-us/library/system.net.http.httpclient(v=vs.118).aspx) and (in most cases) a [HttpClientHandler](https://msdn.microsoft.com/en-us/library/system.net.http.httpclienthandler(v=vs.118).aspx). If you want to use a proxy, you just have to set the `HttpClientHandler`'s properties accordingly.

```csharp
var proxy = new WebProxy("http://proxy-adress.tld:8080");

var client = new HttpClient(new ClearanceHandler(new HttpClientHandler
{
    Proxy = proxy,
    UseProxy = true
}));
```

**Comment by ghost** [comment]
Thanks !
