### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by dderakhshani** [elcattivo/CloudFlareUtilities#16]
Just it doesn't work

**Comment by elcattivo** [comment]
Can you please provide more details?

**Comment by kryptodev** [comment]
The request seems to hang for me. It was working before though.

As in, it makes the request, and then it doesn't complete, just pretty much stuck if you will.

**Comment by elcattivo** [comment]
It is working fine with all my usual test sites. Can you tell my what site doesn't work for you?
