### ISSUE TITLE
Storing sessions

### ISSUE THREAD

**Issue by Cacherd** [elcattivo/CloudFlareUtilities#17]
EDIT:

I have resolved this already by storing the vars properly.

Hi,

I have been using this library for a while and it works perfectly fine.
However, I am interested in optimizing my search speeds.

I am using an API which is located on a server which uses CloudFlare. The CloudFlare clearance takes relatively long for every short search query on the webserver.

I would like to store a session which I have created, so I could access the endpoint during the current session (which lasts about 30 minutes), without having to await the clearance for each lookup.

I have tried the following:

```
var cookieContainer = new CookieContainer();
using (var handler = new ClearanceHandler())
using (var client = new HttpClient(handler, false))
{
var result = await client.GetStringAsync("http://myapiwebsite.com/apiendpoint");
}
```

However, by using this, I still have to await the clearance with every search I run. Is there a way to store the current session and use it while it lasts?

**Comment by utkuerturk** [comment]
Hi , can you share your solution with code snippet.

Thanks
