### ISSUE TITLE
Custom innerHandler not working

### ISSUE THREAD

**Issue by hequs** [elcattivo/CloudFlareUtilities#2]
Hello! 

First of all, thank you for this helpful library!

I have an issue with retrieving cookies from server response. As far as I understand, I have to pass HttpClientHandler object as an innerHandler parameter of the ClearanceHandler class constructor, and then extract cookies from CookieCollection.

Unfortunately, the server responds with 503 HTTP error code while using custom innerHandler:
```
var cookieContainer = new CookieContainer();
var innerHandler = new HttpClientHandler {CookieContainer = cookieContainer};
var handler = new ClearanceHandler(innerHandler);
var client = new HttpClient(handler);
```

Otherwise everything is okay (200).
```
var handler = new ClearanceHandler();
var client = new HttpClient(handler);
```
Regards, Vadim.

**Comment by elcattivo** [comment]
Hi Vadim,

thank you. I'm glad some people find the library useful.

Does the 503 error occur every time you use a custom inner handler or does it arise infrequently?

Your code snippet looks good and should work just fine. However, the ClearanceHandler isn't 100 % reliable at the current stage of development. Sometimes no clearance cookie is returned, which causes a 503 error.

I'm going to implement an auto-retry feature in the next release that will work around this issue until I find out the reason for this behavior.

**Comment by artmasters200** [comment]
Hello!

I tried your library but when I visit https://sarahserver.net/?module=vendor, it gives me runtime error in this line

```
var content = client.GetStringAsync(target).Result;
```

> Response status code does not indicate success: 503 (Service Temporarily Unavailable).

**Comment by elcattivo** [comment]
I still haven't figured out why clearance sometimes (ca. 15 % of all cases) fails. As a workaround, I have implemented an auto-retry-mechanism, which will retry clearance if it fails. You can specify how many retries will be made (default = 3).

If clearance still fails, a ```CloudFlareClearanceException``` exception will be thrown.

Each clearance attempt will take about five seconds. Remember that when you increase the number of retires. Maybe you will have to adapt the ```HttpClient```'s [```Timeout```](https://msdn.microsoft.com/en-us/library/system.net.http.httpclient.timeout(v=vs.110).aspx) property to prevent a ```TaskCanceledException``` exception.
