### ISSUE TITLE
Doesn't even compile in Visual Studio

### ISSUE THREAD

**Issue by turbosupramk3** [elcattivo/CloudFlareUtilities#22]
VSE 2013 desktop.

This doesn't even compile, let alone function. Some of the code doesn't even look like c#

"public CloudFlareClearanceException(int attempts) : this(attempts, $"Clearance failed after {attempts} attempt(s).") { }"

^ unexpected character "$"

**Comment by elcattivo** [comment]
Well, [if you use a more up to date version of Visual Studio, it will compile](https://stackoverflow.com/a/43084947). The `$` character that causes you trouble is used for [String Interpolation](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/interpolated-strings), a feature of C# 6.
