### ISSUE TITLE
Bittrex Websocket again...

### ISSUE THREAD

**Issue by junkomatic** [elcattivo/CloudFlareUtilities#23]
I have been using CloudFlareUtilities with the custom websocketSharp wrapper to access Bittrex websocket feeds, but for some reason it stopped working again today, and I am not sure why: 

Unhandled Exception: System.AggregateException: One or more errors occurred. ---> Microsoft.AspNet.SignalR.Client.HttpClientException: StatusCode: 503, ReasonPhrase: 'Service Temporarily Unavailable', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
  Transfer-Encoding: chunked
  Connection: close
  X-Frame-Options: SAMEORIGIN
  Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
  CF-RAY: 3debad8c5f1b4fff-DEN
  Cache-Control: no-cache
  Date: Wed, 17 Jan 2018 19:21:30 GMT
  Server: cloudflare
  Content-Type: text/html; charset=UTF-8
}

**Comment by deluvas** [comment]
The server name header changed from `cloudflare-nginx` to `cloudflare`. Older version of the library only recognize the former. Only the net standard version knows both and works. 

So you can either use the latest (net standard) or fork an older one and modify the following.

````C#
private static bool IsClearanceRequired(HttpResponseMessage response)
        {
            //var isServiceUnavailable = response.StatusCode == HttpStatusCode.ServiceUnavailable;
            //var isCloudFlareServer = response.Headers.Server.Any(i => i.Product != null && i.Product.Name == CloudFlareServerName);

            //return isServiceUnavailable && isCloudFlareServer;
            var isServiceUnavailable = response.StatusCode == HttpStatusCode.ServiceUnavailable;
            var isCloudFlareServer = response.Headers.Server
                .Any(i => i.Product != null && CloudFlareServerNames.Any(s => string.Compare(s, i.Product.Name, System.StringComparison.OrdinalIgnoreCase) == 0));

            return isServiceUnavailable && isCloudFlareServer;
        }
````

**Comment by junkomatic** [comment]
I will likely do the later, as the SignalR server used by Bittrex is not compatible with net standard. Will close when I finish that.
