### ISSUE TITLE
Locking up in UI thread

### ISSUE THREAD

**Issue by JKorf** [elcattivo/CloudFlareUtilities#27]
Hi, thanks for the library, it works perfectly. I run into a little issue though. When adding a clearancehandler to a HttpClient and calling `await client.SendAsync(msg).ConfigureAwait(false);` from a UI thread it will create a dead lock because internally the clearancehandler doesn't add `.ConfigureAwait(false)` to its calls:

https://github.com/elcattivo/CloudFlareUtilities/blob/d10319438515f8b3f08962c1d8f4e2a9bf603f16/CloudFlareUtilities/ClearanceHandler.cs#L83

https://github.com/elcattivo/CloudFlareUtilities/blob/d10319438515f8b3f08962c1d8f4e2a9bf603f16/CloudFlareUtilities/ClearanceHandler.cs#L93

https://github.com/elcattivo/CloudFlareUtilities/blob/d10319438515f8b3f08962c1d8f4e2a9bf603f16/CloudFlareUtilities/ClearanceHandler.cs#L166

https://github.com/elcattivo/CloudFlareUtilities/blob/d10319438515f8b3f08962c1d8f4e2a9bf603f16/CloudFlareUtilities/ClearanceHandler.cs#L174

Any chance the .ConfigureAwait could be added to these calls?

**Comment by mesta1** [comment]
Can you update the nuget ?

**Comment by JKorf** [comment]
Works with the latest version, thanks for the quick fix!
