### ISSUE TITLE
Proxies not working anymore ?

### ISSUE THREAD

**Issue by kdcz** [elcattivo/CloudFlareUtilities#34]
Hello, first thank you for your awesome work.
I was able to use proxies through the innerHandler but since yesterday it seems that it doesn't works anymore, I keep getting failed challenges(403) and what's weird is that the challenges are solved on my IP ignoring the proxy settings(but the "initial" request to the website is done(503) with the proxy settings) which was not the case before.
I am using the latest version and it works fine on my local ip.

Thank you

**Comment by kdcz** [comment]
nevermind it's my proxies that got "banned" and are getting captchas challenges my bad

**Comment by JamesMaxwel** [comment]
Could you share your code? I am trying to use proxy but I am not able to declare.
