### ISSUE TITLE
I am so new 

### ISSUE THREAD

**Issue by danial1964** [elcattivo/CloudFlareUtilities#4]
hello im so new in programming. i want use this tool. so i installed visual studio 2015 for first time in my life. then i installed this project in my visual studio by double click on **CloudFlareUtilities.sln** . 
then i installed with `Install-Package CloudFlareUtilities -Pre` command succesfully.
now i dont know what i have to do?? how to use this usage code:
`try
{
    // Create the clearance handler.
    var handler = new ClearanceHandler
    {
        MaxRetries = 2 // Optionally specify the number of retries, if clearance fails (default is 3).
    };

    // Create a HttpClient that uses the handler to bypass CloudFlare's JavaScript challange.
    var client = new HttpClient(handler);

    // Use the HttpClient as usual. Any JS challenge will be solved automatically for you.
    var content = await client.GetStringAsync("http://protected-site.tld/");
}
catch (AggregateException ex) when (ex.InnerException is CloudFlareClearanceException)
{
    // After all retries, clearance still failed.
}
catch (AggregateException ex) when (ex.InnerException is TaskCanceledException)
{
    // Looks like we ran into a timeout. Too many clearance attempts?
    // Maybe you should increase client.Timeout as each attempt will take about five seconds.
}`
i want use this project for a https site. plz plz plz plz guide me guys. i worked few days on this tool but i still dont know what i have to do and if you make a video guide is soooo greate work. sorry for my bad english

**Comment by elcattivo** [comment]
Please take a look at the [```ClearanceExample```](https://github.com/elcattivo/CloudFlareUtilities/tree/master/CloudFlareUtilities.ClearanceExample) project. Maybe this will give you a hint. In the ```Program.cs``` replace ```args[0]``` with the URL of the website you want to access. The example code will get the HTML code of the given website, extract its title using regular expression and print it on the console.

**Comment by danial1964** [comment]
thank you for answer😀. i replaced arg[0] with URL and i succesfully biuld
that but i got error when i click on start button 😖. plz take a look at
pictures.🙏

**Comment by danial1964** [comment]
![untitled](https://cloud.githubusercontent.com/assets/21980156/18237538/38643404-7348-11e6-8b96-7d06d7e437f3.png)
![untitled1](https://cloud.githubusercontent.com/assets/21980156/18237539/38667b42-7348-11e6-9d98-8887e089a0a3.png)

**Comment by elcattivo** [comment]
Right click on the example project and make it the startup project.

**Comment by danial1964** [comment]
hello.thanks for answer. cmd will come up for me and then gone so fast and will show me nothing  :((
![untitled](https://cloud.githubusercontent.com/assets/21980156/18283964/29c83ce8-747d-11e6-9087-ada3a4e06e93.png)

**Comment by elcattivo** [comment]
http://stackoverflow.com/questions/1775865/preventing-console-window-from-closing-on-visual-studio-c-c-console-applicatio

If you have further general questions about C#, .NET Framework or Visual Studio please buy a book about these topics, read some online HowTos/Tutorials or use the search engine of your choice.

In case you have a specific question about this library, please open another issue.
