### ISSUE TITLE
new challenge version

### ISSUE THREAD

**Issue by Eric898989** [elcattivo/CloudFlareUtilities#40]
The current CloudflareUtilities does not manage to handle the new challenge version, presence of a s parameter in the get /cdn-cgi/l/chk_jschl:

/cdn-cgi/l/chk_jschl?s=xxxxxxx&jschl_vc=yyyyyyyyyyyyyy&pass=zzzzzzzzz&jschl_answer=eeeeeeeee

=> modification needed

**Comment by Bleialf** [comment]
Fixed that and made a pull request. Seems to need about 5 - 10 retries to pass.

**Comment by Eric898989** [comment]
Thanks Bleialf for #41

**Comment by Bleialf** [comment]
Happy to help! Awesome library!
