### ISSUE TITLE
CurlSharp handler

### ISSUE THREAD

**Issue by freddy36** [elcattivo/CloudFlareUtilities#5]
Hello,

I would like to add a new Handler which could be used with CurlSharp (Allowing it to be used e.g. on Linux systems with the libcurl HTTP lib).
Before I waste any time I would like to know if you would accept a corresponding pull request.

**Comment by kaso17** [comment]
Same problem here.

I've already written a wrapper for CurlSharp which uses this lib.
But I had to access the corresponding methods via reflections.
If you could just make the Internal classes public that would make thinks way easier to implement with other HTTP libs.

**Comment by elcattivo** [comment]
Sorry for the delay. @freddy36 a handler for CurlSharp would certainly be useful, but I don't think it would fit into this library. As @kaso17 suggested, I will make the classes, that are used for solving the JS challenge, public, so you can make use of the lib without depending on the `CleranceHandler` or reflection. That way, creating specific handlers in other libraries/projects should no longer be a problem.

**Comment by kaso17** [comment]
Here's an example how to use the currently internal methods via reflections as a wrapper around another HTTP lib:
https://github.com/Jackett/Jackett/pull/538/commits/2254363840f65c6c4d5299cc34a672696cabd25d

**Comment by elcattivo** [comment]
The required classes are now public.
