### ISSUE TITLE
Stopped working after about 10 times

### ISSUE THREAD

**Issue by jdlovins** [elcattivo/CloudFlareUtilities#8]
Hey, after a few times it seems this no longer works. I tried changing the User Agent thinking that may have been it but no luck. I used a python library which seemed to work just fine. I also tried with different sites as well. 

Does it still work fine for you?

**Comment by elcattivo** [comment]
Still working fine for me. Can you give a little bit more detail about what is not working for you? Maybe you can even provide an example program that can reproduce the problem.

**Comment by jdlovins** [comment]
Sure, this is what I'm using https://github.com/jdlovins/cloudflarecookies
All that I changed was so I could grab the 2 cookie after it succeeded. Does cloudflare blacklist IPs or something? I had run the program quite a few times in a short period of time so I'm not sure.

**Comment by elcattivo** [comment]
The following line is missing at https://github.com/jdlovins/cloudflarecookies/blob/81e736d20f3dc07a3823eff4154ef5c986f1d5d1/CloudFlareUtilities/ClearanceHandler.cs#L165:

```csharp
await _client.SendAsync(clearanceRequest, cancellationToken);
```

**Comment by jdlovins** [comment]
Wow, I must have accidentally removed that when messing around with user agent stuff. That worked instantly. Thanks so much!
